### ISSUE TITLE
Include help in README

### ISSUE THREAD

**Issue by gasche** [jonathanyc/car#2]
I just learned of this project from [Categoria's reddit post](https://www.reddit.com/r/ocaml/comments/4bk7ro/car_a_collection_of_aliases_for_common_tasks_on/), I read the README but I'm still confused at what the script can do. Could you maybe include the output of the `help ()` function inside the README itself?

**Comment by jyc** [comment]
Hi! Sorry, not sure how I didn't see this. Yes, that is a good idea. I hope to improve the documentation soon. Also, I wrote this after working on some small projecrs, but have recently been trying it on a much bigger project with others and have ran into some things I think I ought to change. So the two will probably go hand-in-hand.

Didn't expect this script to end up on Reddit of all places! 😊

**Comment by lezed1** [comment]
I just created a pull request with the help text in the README. @jonathanyc: Would you merge this?

**Comment by jyc** [comment]
Thanks @lezed1. Sorry for the very delayed reply. I should have more time to work on this soon, including adding better documentation.
